### PR TITLE
if season returns null from netflix

### PR DESCRIPTION
**Pull request by chrillep**
for special shows like "maniac" who return "Limited Series" as "Season"

### CODE REVIEW

**Comment by Gerst20051** [comment]
this MR can probably be closed

**Comment by chrillep** [comment]
the fail isn't because of the PR

**Comment by gsrafael01** [comment]
I didn't implement this specifically, but I don't think there's a problem, as the Netflix API returns `"seq":1` for Maniac (and I'd assume for any limited series): https://www.netflix.com/api/shakti/ve24f6569/metadata?languages=en-US&movieid=80124522 So it's already defaulted to 1. I just tested and it scrobbles that show with no problems.

**Comment by tegon** [comment]
Going to close it then. Thanks!

**Pull request closed without merging**
