### PR TITLE
Firefox compatibility and many improvements

### PR DESCRIPTION
**Pull request by gsrafael01**
* Made the extension compatible with Firefox
* Migrated the modules to E6 and implemented many E6 features
* Migrated development to Webpack, because I'm more familiar with it than Gulp
* Fixed the tests and migrated them to Mocha + Chai, because this combination allows for some cool testing features that Jasmine does not have
* Added a PT-BR locale
* Added an options menu, to allow users to opt-in to Google Analytics and Rollbar instead of making them enabled by default, which is a privacy concern since GDPR
* Added an option to disable scrobbling in real time, in case the user wants to sync their history when they wish
* Improved the loading time of the activity history, by loading things asynchronously and implementing a cache
* Implemented a Google Sheets database for the history sync, so that if a user corrects an item all other users will receive suggestions for the same correction
* Made it so that the sync checkbox is disabled if the item was not found on Trakt in the history sync, to prevent errors when syncing
* Improved UI error handling when updating an item in the history sync (it now shows messages to the user to let them know what is going on)
* Started using Netflix' API instead of scraping the HTML of the page to get information about the item that the user is watching
* Made it so that requests to the Netflix API are made in English, which should allow the extension to work well for users using non-English Netflix most of the times
* Improved the detection of episode titles
* Fixed the detection of collections
* ...

### CODE REVIEW

**Comment by gsrafael01** [comment]
Coverage decreasing is because of the new functionality that I haven't added tests for yet, but I can do that as well.

**Comment by tegon** [comment]
@gsrafael01 No problem, the test can be added in a new pull request if that's the case.

Since the changes are too big, I can't do a properly review so I'm going to accept the pull request and try the app later.

Thanks!

**Comment by gsrafael01** [comment]
There might be a few things to fix for it to fully work properly with Chrome though, I'll see if I can perform some tests soon.

**Comment by gsrafael01** [comment]
I just released a new version that uses `launchWebAuthFlow` like the old version did: https://github.com/gsrafael01/traktflix/tree/2.0.6

I'm not sure how to make a PR for this. When I try making a PR it includes all of the commits that have already been merged. :S

**Comment by gazpachoking** [comment]
@gsrafael01 Your commits from this PR got squashed when merging, which is why they are showing up again when you try to make a new PR. You'll need to check out the latest from this repo, then apply your new changes to that.

**Comment by gsrafael01** [comment]
Thanks, @gazpachoking! I'll do that.

**Pull request merged**
